apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryasg7404.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: sqlserverasg7404.database.windows.net
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP