kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-read-api-namespace-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: User
  namespace: api
  name: webdev@msftopenhack6979ops.onmicrosoft.com

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-write-web-namespace-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: User
  namespace: web
  name: webdev@msftopenhack6979ops.onmicrosoft.com

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-web-namespace-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: User
  namespace: web
  name: apidev@msftopenhack6979ops.onmicrosoft.com

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-write-api-namespace-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: User
  namespace: api
  name: apidev@msftopenhack6979ops.onmicrosoft.com
