kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-read-api
  namespace: api
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","watch","list"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-write-web
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","watch","list", "create", "update", "patch", "delete"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-read-web
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","watch","list"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-write-api
  namespace: api
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get","watch","list", "create", "update", "patch", "delete"]

